### ISSUE TITLE
Tray Menu Crash

### ISSUE THREAD

**Issue by dtext** [instantshare/instantshare#38]
After taking a cropped screenshot, the screenshot was uploaded, but then the tray menu crashed.

Relevant Part of the stack trace:

```
  File "C:/Users/dt/Projects/python/instantshare/src\cli\main.py", line 76, in main
    _execute_command(argv)
  File "C:/Users/dt/Projects/python/instantshare/src\cli\main.py", line 52, in _execute_command
    _get_module(argv[0]).main(argv)
  File "C:/Users/dt/Projects/python/instantshare/src\cli\gui.py", line 63, in main
    event()
TypeError: 'NoneType' object is not callable
```

Somehow, `None` must have ended up in the event queue from somewhere.
This happened with the imgur storage provider enabled, but that does not seem to be related to this.

Edit: as mentioned in #39, this occurred after I had that other issue and ran `instantshare tray` to work around that.

**Comment by dtext** [comment]
This happens reliably everytime I use take a cropped screenshot from the tray menu.
I am using the default configuration. Seems to be independent from #39 and the selected storage provider.

Full log this time:

```
2016-09-13 22:35:19,471 INFO:   Creating tray icon for instantshare
2016-09-13 22:35:32,366 INFO:   Starting new HTTPS connection (1): api.imgur.com
2016-09-13 22:35:33,558 INFO:   Starting new HTTPS connection (1): api.imgur.com
2016-09-13 22:35:34,644 INFO:   Uploaded screenshot to: http://i.imgur.com/qJyUMAP.png
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.2\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.2\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/dt/Projects/python/instantshare/src/instantshare", line 3, in <module>
    main()
  File "C:/Users/dt/Projects/python/instantshare/src\cli\main.py", line 76, in main
    _execute_command(argv)
  File "C:/Users/dt/Projects/python/instantshare/src\cli\main.py", line 52, in _execute_command
    _get_module(argv[0]).main(argv)
  File "C:/Users/dt/Projects/python/instantshare/src\cli\gui.py", line 63, in main
    event()
TypeError: 'NoneType' object is not callable
```

Maybe it's noteworthy that it happens about 2, 3 seconds after the upload is finished.

**Comment by florianluediger** [comment]
I am getting the same error, too, so it's not just you. We could easily work around that by replacing line 63 with:

```
if callable(event):
    event()
```

If you agree on this, I will publish this fix.
